### ISSUE TITLE
Docker Container Usability Affected by Dynamic Xauthority File Name

### ISSUE THREAD

**Issue by manojm-dev** [RishikesavanRamesh/ROS2-DEV#1]
# Docker Container Usability Affected by Dynamic Xauthority File Name

## Description:

I have encountered an issue with the[ Docker Compose](https://github.com/RishikesavanRamesh/ROS2-DEV/blob/e138a158a3e7f9d9200da0e9fd9439efdb33422e/.devcontainer/ros2/compose.yml) setup where the XAUTHORITY file used for mounting into the container has a dynamically generated name, which includes random characters. This results in the container becoming unusable after a restart, as the container expects a consistent file name.

## Problem:
- The current XAUTHORITY file path in the Docker Compose file is set to ${XAUTHORITY:-$HOME/.Xauthority}. However, this results in the file having a name with random characters, such as xauth_kjdkfjdkf.
- When the container is restarted, it cannot find or use the existing Xauthority file, leading to issues with container usability.
- This problem necessitates a rebuild of the container after each restart to restore functionality.

## Steps to Reproduce:

- Start the Docker Compose setup with the current configuration.
- Observe the dynamically generated XAUTHORITY file name.
- Restart the pc/laptop.
- Note that the container becomes unusable due to the missing or inconsistent Xauthority file.

## Expected Behavior:

The container should be able to use X11 forwarding without issues related to a dynamically named XAUTHORITY file.

### Suggested Solution:

Instead of mounting the Xauthority file, use xhost to grant access for the local user:

1) Run the following command on the host system to allow the local user to connect to the X server:

```
# add this to ~/.profiles
xhost +SI:localuser:$USER
```
2) Modify the Docker Compose configuration to remove the Xauthority file mounting:

```
# Remove the line for mounting .Xauthority
# - ${XAUTHORITY:-$HOME/.Xauthority}:/home/developer/.Xauthority
```
3) Ensure that the Docker container is properly configured for X11 forwarding without relying on the Xauthority file

**Comment by manojm-dev** [comment]
Fixed this issue in this [PR](https://github.com/RishikesavanRamesh/ROS2-DEV/pull/2)

**Comment by RishikesavanRamesh** [comment]
[XEPHYR](https://gist.github.com/RishikesavanRamesh/d8c085c958bc11e8562cd3db297e4eb8) will be used instead of disabling xhost security, in the humble branch.
